allowBuilds:
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - prettier@3.9.6
patchedDependencies:
  nextra-theme-docs@4.6.1: patches/nextra-theme-docs@4.6.1.patch
